[
    {
        "content": "<p>On <a href=\"https://github.com/leanprover-community/mathlib4/pull/7831\">#7831</a>, I’m testing out a lean4 pr release in mathlib, and it seems to have run into an error while downloading the release. Excerpted from the failure message (see PR):</p>\n<div class=\"codehilite\" data-code-language=\"null\"><pre><span></span><code>info: downloading component 'lean'\nerror: could not download file from 'https://github.com/leanprover/lean4-pr-releases/releases/expanded_assets/pr-release-2728' to '/home/velcom/.elan/tmp/_2astaa07f4xkl6n_file'\ninfo: caused by: error during download\ninfo: caused by: [35] SSL connect error (Recv failure: Connection reset by peer)\n</code></pre></div>\n<p>(I tried just commenting !bench again, but to no avail.)</p>\n<p>Interestingly, this isn’t a general problem: another PR using a lean4 pr release benched just fine just before (<a href=\"https://github.com/leanprover-community/mathlib4/pull/7830\">#7830</a>).</p>",
        "id": 397974298,
        "sender_full_name": "Thomas Murrills",
        "timestamp": 1698011433
    },
    {
        "content": "<p>Can you install the toolchain locally?</p>\n<p>If no, just regenerate the toolchain by touching the Lean4 brnach.</p>\n<p>If yes, we might have to summon Sebastian as it would be a speedcenter issue.</p>",
        "id": 397974396,
        "sender_full_name": "Scott Morrison",
        "timestamp": 1698011623
    },
    {
        "content": "<p>I’ll try in a bit, as I’m on mobile right now. :) I will note that the mathlib4 PR built just fine with the toolchain (but I’m not sure if that’s the same machine that made the toolchain or what’s going on behind the scenes)</p>",
        "id": 397974599,
        "sender_full_name": "Thomas Murrills",
        "timestamp": 1698011906
    },
    {
        "content": "<p>Yep, turns out I can install this toolchain locally with no problem.</p>",
        "id": 397992385,
        "sender_full_name": "Thomas Murrills",
        "timestamp": 1698026653
    },
    {
        "content": "<p>Oh, but you didn't push anything in between running <code>!bench</code>, so it is just using the cached failure. Push an empty commit and try again.</p>",
        "id": 398001854,
        "sender_full_name": "Scott Morrison",
        "timestamp": 1698031620
    },
    {
        "content": "<p>(For the record, just redoing the bench like this worked; I guess it just needed a jolt. :) )</p>",
        "id": 398033861,
        "sender_full_name": "Thomas Murrills",
        "timestamp": 1698048798
    }
]