[
    {
        "content": "<p>Quite a few of my recent CI runs have failed with \"PANIC index out of bounds\".  I don't know if it's the actual material in the commits (I've been trying to bisect to no avail), some git magic above my usual paygrade which I attempted, or a random fluke.  Has anyone seen this before?</p>\n<p>If someone is willing to investigate, you can compare<br>\n<a href=\"https://github.com/leanprover-community/mathlib4/compare/rel_congr2\">https://github.com/leanprover-community/mathlib4/compare/rel_congr2</a> (builds ok)<br>\nwith<br>\n<a href=\"https://github.com/leanprover-community/mathlib4/compare/rel_congr_golfs2\">https://github.com/leanprover-community/mathlib4/compare/rel_congr_golfs2</a> (5 commits later most of which are attempts to circumvent the panicking)</p>",
        "id": 357441053,
        "sender_full_name": "Heather Macbeth",
        "timestamp": 1683772228
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"260507\">Heather Macbeth</span> <a href=\"#narrow/stream/287929-mathlib4/topic/PANIC.20index.20out.20of.20bounds/near/357441053\">said</a>:</p>\n<blockquote>\n<p>I don't know if it's the actual material in the commits (I've been trying to bisect to no avail)</p>\n</blockquote>\n<p>My current experiments suggest it's indeed the actual material in the commits, so maybe no need for help just now.</p>",
        "id": 357455955,
        "sender_full_name": "Heather Macbeth",
        "timestamp": 1683778358
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"260507\">Heather Macbeth</span> has marked this topic as resolved.</p>",
        "id": 357460678,
        "sender_full_name": "Notification Bot",
        "timestamp": 1683781041
    }
]