[
    {
        "content": "<p>I was making minor edits to the file <code>Analysis.NormedSpace.OperatorNorm</code> when suddenly the sidebar turned red and I got the following error pop-up:</p>\n<div class=\"codehilite\" data-code-language=\"Lean\"><pre><span></span><code><span class=\"n\">Lean</span> <span class=\"n\">server</span> <span class=\"n\">printed</span> <span class=\"n\">an</span> <span class=\"n\">error</span><span class=\"o\">:</span> <span class=\"n\">libc</span><span class=\"bp\">++</span><span class=\"n\">abi.dylib</span><span class=\"o\">:</span> <span class=\"n\">terminating</span> <span class=\"k\">with</span> <span class=\"n\">uncaught</span>\n<span class=\"n\">exception</span> <span class=\"n\">of</span> <span class=\"n\">type</span> <span class=\"n\">lean</span><span class=\"o\">::</span><span class=\"n\">heartbeat_exception</span><span class=\"o\">:</span> <span class=\"o\">(</span><span class=\"n\">deterministic</span><span class=\"o\">)</span> <span class=\"n\">timeout</span>\n</code></pre></div>\n<p>Is this a problem of mine locally (is there some setting I need to adjust) or a problem with mathlib?</p>",
        "id": 367768089,
        "sender_full_name": "Heather Macbeth",
        "timestamp": 1687218897
    },
    {
        "content": "<p>If relevant, <a href=\"https://github.com/leanprover-community/mathlib4/tree/timeout-operator-norm\">here</a>'s the branch.</p>",
        "id": 367768424,
        "sender_full_name": "Heather Macbeth",
        "timestamp": 1687219184
    },
    {
        "content": "<p>... the branch seems to be compiling fine, so I guess it's an issue on my end?  Anyone know what VS Code setting I might need to change?</p>",
        "id": 367768900,
        "sender_full_name": "Heather Macbeth",
        "timestamp": 1687219518
    },
    {
        "content": "<p>It appears a timeout exception was thrown somewhere where lean was not expecting it and the exception was not caught leading to a process crash</p>",
        "id": 367773656,
        "sender_full_name": "Mario Carneiro",
        "timestamp": 1687222113
    },
    {
        "content": "<p>unfortunately the error message gives basically no clue as to where that might be</p>",
        "id": 367773691,
        "sender_full_name": "Mario Carneiro",
        "timestamp": 1687222139
    },
    {
        "content": "<p>(this is why timeouts probably shouldn't be exceptions, since literally any code can take time and result in a timeout)</p>",
        "id": 367773769,
        "sender_full_name": "Mario Carneiro",
        "timestamp": 1687222179
    },
    {
        "content": "<p>your error is unlikely to be reproducible, even by you</p>",
        "id": 367773892,
        "sender_full_name": "Mario Carneiro",
        "timestamp": 1687222217
    },
    {
        "content": "<p>If these things aren't reproducible, should the error messages include a traceback of some kind?</p>",
        "id": 367774026,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1687222299
    },
    {
        "content": "<p>So that we stand some chance of spotting where the exception wasn't handled</p>",
        "id": 367774151,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1687222332
    },
    {
        "content": "<p>well, the exception \"wasn't handled\" at <code>main</code></p>",
        "id": 367774516,
        "sender_full_name": "Mario Carneiro",
        "timestamp": 1687222515
    },
    {
        "content": "<p>probably not a very useful thing to report</p>",
        "id": 367774545,
        "sender_full_name": "Mario Carneiro",
        "timestamp": 1687222529
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"110049\">Mario Carneiro</span> <a href=\"#narrow/stream/287929-mathlib4/topic/timeouts/near/367773892\">said</a>:</p>\n<blockquote>\n<p>your error is unlikely to be reproducible, even by you</p>\n</blockquote>\n<p>Maybe this literal error is not reproducible, but I have tried basically the same thing (golfing in <code>OperatorNorm</code> using <code>gcongr</code>) several times in the last few weeks and hit this kind of timeout every time.</p>",
        "id": 367775860,
        "sender_full_name": "Heather Macbeth",
        "timestamp": 1687223134
    },
    {
        "content": "<p>In any case, on my machine I think it is reproducible?  At least, I've tried twice to open the file in the state indicated in that branch and got the timeout both times ...</p>",
        "id": 367775990,
        "sender_full_name": "Heather Macbeth",
        "timestamp": 1687223186
    },
    {
        "content": "<p>Unfortunately, I couldn't reproduce this one. (By checking out the branch <code>timeout-operator-norm</code>, running <code>lake exe cache get</code>, and opening <code>Analysis.NormedSpace.OperatorNorm</code> in VSCode.)</p>",
        "id": 367778258,
        "sender_full_name": "Scott Morrison",
        "timestamp": 1687224260
    },
    {
        "content": "<p>That's frustrating.  I just tried those steps again and got the timeout again.</p>",
        "id": 367780186,
        "sender_full_name": "Heather Macbeth",
        "timestamp": 1687225340
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"110049\">Mario Carneiro</span> <a href=\"#narrow/stream/287929-mathlib4/topic/timeouts/near/367774516\">said</a>:</p>\n<blockquote>\n<p>well, the exception \"wasn't handled\" at <code>main</code></p>\n</blockquote>\n<p>Well, arguably also at every frame up the call stack, with the interesting bits in the middle...</p>",
        "id": 367823079,
        "sender_full_name": "Eric Wieser",
        "timestamp": 1687245269
    },
    {
        "content": "<p>Could it be Heather's local VS Code settings? Heather can you reproduce on the command line?</p>",
        "id": 367826211,
        "sender_full_name": "Kevin Buzzard",
        "timestamp": 1687246075
    }
]