[
    {
        "content": "<p>I just saw <a href=\"https://github.com/leanprover-community/mathlib4/actions/runs/7150461236/job/19473764324\">an insane job</a> where the runner printed out</p>\n<div class=\"codehilite\" data-code-language=\"Lean\"><pre><span></span><code><span class=\"n\">Warning</span><span class=\"o\">:</span> <span class=\"bp\">./</span><span class=\"n\">Mathlib</span><span class=\"bp\">/</span><span class=\"n\">Algebra</span><span class=\"bp\">/</span><span class=\"n\">Support.lean</span> <span class=\"n\">not</span> <span class=\"n\">found.</span> <span class=\"n\">Skipping</span> <span class=\"n\">all</span> <span class=\"n\">files</span> <span class=\"n\">that</span> <span class=\"n\">depend</span> <span class=\"n\">on</span> <span class=\"n\">it</span>\n</code></pre></div>\n<p>for 6 hours. Arguably, the PR is not building (I am moving <code>Algebra.Support</code> to <code>Algebra.Support.Basic</code> and forgot to update some of the <code>import Mathlib.Algebra.Support</code>), but this still is an impressive failure mode.</p>",
        "id": 406967784,
        "sender_full_name": "Yaël Dillies",
        "timestamp": 1702152571
    },
    {
        "content": "<p>I have seen this issue before, there was a bug fix to cache to fix it. How old is the mathlib branch you are testing?</p>",
        "id": 406971180,
        "sender_full_name": "Mario Carneiro",
        "timestamp": 1702156071
    },
    {
        "content": "<p>It's <a href=\"https://github.com/leanprover-community/mathlib4/tree/sink_support\">branch#sink_support</a> whose latest master commit is <a href=\"https://github.com/leanprover-community/mathlib4/commit/5d4fa55028ca22525074d4c2141f8f2a04dc0e32\">https://github.com/leanprover-community/mathlib4/commit/5d4fa55028ca22525074d4c2141f8f2a04dc0e32</a> from earlier today.</p>",
        "id": 406971306,
        "sender_full_name": "Yaël Dillies",
        "timestamp": 1702156174
    },
    {
        "content": "<p>wait a minute, the bug fix never landed</p>",
        "id": 406971500,
        "sender_full_name": "Mario Carneiro",
        "timestamp": 1702156344
    },
    {
        "content": "<p>now I have to find where it ended up</p>",
        "id": 406971513,
        "sender_full_name": "Mario Carneiro",
        "timestamp": 1702156357
    },
    {
        "content": "<p><a href=\"https://github.com/leanprover-community/mathlib4/pull/7876\">#7876</a></p>",
        "id": 406971570,
        "sender_full_name": "Mario Carneiro",
        "timestamp": 1702156430
    },
    {
        "content": "<p>Well I cherry picked that commit to <code>sink_support</code> and it fixes the infinite loop so I'm going to call that a successful test</p>",
        "id": 406971695,
        "sender_full_name": "Mario Carneiro",
        "timestamp": 1702156526
    },
    {
        "content": "<p>(Note that this only happens when you import a file that doesn't exist, so it would have already failed for other reasons)</p>",
        "id": 406971868,
        "sender_full_name": "Mario Carneiro",
        "timestamp": 1702156707
    }
]